name: Exemplo de CI # Nome do workflow

on:
  push: # Evento que dispara o workflow
    branches: [ main ] # Branch que dispara o workflow

jobs:
  build: # Primeiro trabalho: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Passo para clonar o repositório
        uses: actions/checkout@v4

      - name: Set up JDK 17 # Configuração do JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven # Build do projeto com Maven
        run: mvn -B package -DskipTests

  tests: # Segundo trabalho: Testes
    runs-on: ubuntu-latest
    needs: build # Dependência do trabalho 'build'
    steps:
      - name: Checkout code # Passo para clonar o repositório
        uses: actions/checkout@v4

      - name: Set up JDK 17 # Configuração do JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Tests # Executa os testes
        run: mvn test
